### PR TITLE
Provide ability to activate or not the error messages auto displaying

### PR DESCRIPTION
**Pull request by Okipa**
Related to https://github.com/realrashid/sweet-alert/issues/64

### CODE REVIEW

**Comment by realrashid** [comment]
Hey @Okipa let me review it.
Then i will tag a new release 😉

**Comment by Okipa** [comment]
Thanks @realrashid, looking foward your release then !

**Comment by realrashid** [comment]
Thank you for your contribution 😍

**Comment by Okipa** [comment]
Thanks to you !

By the way, it seems that the doc is not updated when a PR is merged : https://realrashid.github.io/sweet-alert/#/middleware?id=middleware

**Comment by realrashid** [comment]
It's updated 😊
You have to hard reload the docs.

**Pull request merged**
