### PR TITLE
Add new logos

### PR DESCRIPTION
**Pull request by ericlbarnes**
Created some new "candy alert" style logos for the package. 

logo-small

logo-donut@2x

logo-large

What do you think?

### CODE REVIEW

**Comment by realrashid** [comment]
It's great man.
I like that donut one but can the sweet alert text on that 😉.

I will use that one on redme as well in docs too.

Thank for your contribution man.

**Comment by ericlbarnes** [comment]
Done. I didn't have the actual source of the donut so it's not perfectly crisp. 

logo

**Comment by realrashid** [comment]
Hey @ericlbarnes ,

If you don't mind i will add Logo design by [Eric L. Barnes](https://ericlbarnes.com) on the Credits section of docs.

**Comment by ericlbarnes** [comment]
Sounds great! Thanks again for allowing me to help.

**Pull request merged**
