### PR TITLE
Same thing refactored

### PR DESCRIPTION
**Pull request by thewebartisan7**
Just a little bit more short.

### CODE REVIEW

**Comment by realrashid** [comment]
Hey @thewebartisan7 ,

Thank you for contributing in this package :tada: .
But unfortunately i can not accept this PR.
I think you didn't understand what's going on in side `alert.blade.php` let me tell you what's going on in side `alert.blade.php`.

```php
// This is optional step for custom animation
@if(!empty(config('sweetalert.animatecss')) && config('sweetalert.animation.enable'))
    <link rel="stylesheet" href="{{ config('sweetalert.animatecss') }}">
@endif
// This CDN option is also optional it's upto user if they want to use or not.
// Because this package come with pre loaded sweetalert.all.js library
@if (!empty($cdn))
    @if (Session::has('alert.config'))
        <script src="{{ $cdn }}"></script>
        <script>
            Swal.fire({!! Session::pull('alert.config') !!});
        </script>
    @endif
@else
    @if (Session::has('alert.config'))
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js') }}"></script>
    <script>
        Swal.fire({!! Session::pull('alert.config') !!});
    </script>
    @endif
@endif
```

Now come to step how they use the optional options.

If someone don't want to use pre-loaded `sweetalert.all.js` so he/she can use cdn. 
Just passing the cdn variable to `@include('sweetalert::alert')` included view like below example.

```php
@include('sweetalert::alert', ['cdn' => "https://cdn.jsdelivr.net/npm/sweetalert2@9"])
```

In feature i will add more options here.

Hope you know get what's going on in side `alert.blade.php`

**Comment by thewebartisan7** [comment]
I understand how work your code, but I think that you didn't understand my PR.

This code:

```
{{ $cdn?? asset('vendor/sweetalert/sweetalert.all.js')  }}
```

It's the same as your but shorten. It's the new PHP 7 Null coalescing operator `??`, see https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

If $cdn is not isset, then is returned `asset('vendor/sweetalert/sweetalert.all.js')`, when it's issed then is returned $cdn. 

With my PR you can still use:

```
@include('sweetalert::alert', ['cdn' => "https://cdn.jsdelivr.net/npm/sweetalert2@9"])
```

Also in my PR I load CSS animation library only if sweetalert it's enabled and used.

As I said in my first message, it's the same, but just refactored. I tested it.

**Comment by realrashid** [comment]
Oh man!
What i did 😂.
I will merge it soon.

**Comment by realrashid** [comment]
Hey @thewebartisan7 ,
apology for the misconception 😢 .

Thank you for your contribution and for the great refactor in codes. 👍 .

**Pull request merged**
