### PR TITLE
Missing ^ indicator prevents Laravel from updating to 6.0.1 and up.

### PR DESCRIPTION
**Pull request by stefro**

### CODE REVIEW

**Comment by realrashid** [comment]
Thank for your contribution!

**Comment by stefro** [comment]
You’re welcome! Thank you for the great package!

**Comment by stefro** [comment]
Can you please tag a new version? It still prevents from updating Laravel in version 2.0.1.

Thanks!

**Comment by realrashid** [comment]
Hey @stefro i just published a new version.
Have a look.

**Comment by stefro** [comment]
Thanks!

**Pull request merged**
